Algoritmo "Exercicio_4"
// Descrição   : maior ou menor que 0
// Data atual  : 19/03/2024
Var
   numero:inteiro

Inicio
   escreva("Digite um valor inteiro: ")
   leia(numero)
   se (numero > 0 ) entao
      escreva("o numero é positivo" )
   senao
      se (numero < 0 ) entao
         escreva("o numero é negativo" )
      senao
         escreva("o valor é zero, assim nem positivo nem negativo" )
      fimse
   fimse

Fimalgoritmo