Algoritmo "Exercicio_4.3"
// Descrição   : gera a saída de números repetidos
// Data atual  : 09/04/2024
Var
   i,j,colunas,linhas:inteiro


Inicio
   escreva("Digite a quantidade de linhas: ")
   leia (linhas)
   escreva("Digite a quantidade de colunas: ")
   leia(colunas)
   para i de 1 ate linhas passo 1 faca

      para j de 1 ate colunas passo 1 faca
         escreva(i)
      fimpara
      escreval()
   fimpara


Fimalgoritmo