Algoritmo "Exercicio_5"
// Descrição   : Horas do funcionário
// Data atual  : 13/03/2024
Var
horas,valor_hora,salario_total:real
matricula:inteiro


Inicio
escreva("Escreva a matricula do funcionario:")
leia(matricula)
escreva("Quantas horas esse funcionario trabalhou?")
leia(horas)
escreva("Quanto esse funcionario recebe por hora?")
leia(valor_hora)
salario_total <- (horas*valor_hora)
escreva("Salário total = ", salario_total)

Fimalgoritmo